-- ============================================================
-- FontGlyphCatalogData.lua
-- Auto-generated Unicode glyph catalog. Used by FontGlyphViewer
-- to show all glyphs with their English names so user can
-- visually verify which ones render in WoW fonts vs render as
-- tofu / blank squares.
--
-- 15 categories, 812 total glyphs.
-- See wow-coding skill Rule 5 for which glyph classes are unsafe
-- in rendered text.
-- ============================================================

GeRODPS_Tools = GeRODPS_Tools or {}
GeRODPS_Tools.FontGlyphCatalog = {
    {
        title        = "Block Elements",
        unicodeRange = "U+2580 - U+259F",
        notes        = "Full block, half blocks, and shade blocks. Most reliable in fixed-width fonts.",
        entries = {
            { "▀", "U+2580", "UPPER HALF BLOCK" },
            { "▁", "U+2581", "LOWER ONE EIGHTH BLOCK" },
            { "▂", "U+2582", "LOWER ONE QUARTER BLOCK" },
            { "▃", "U+2583", "LOWER THREE EIGHTHS BLOCK" },
            { "▄", "U+2584", "LOWER HALF BLOCK" },
            { "▅", "U+2585", "LOWER FIVE EIGHTHS BLOCK" },
            { "▆", "U+2586", "LOWER THREE QUARTERS BLOCK" },
            { "▇", "U+2587", "LOWER SEVEN EIGHTHS BLOCK" },
            { "█", "U+2588", "FULL BLOCK" },
            { "▉", "U+2589", "LEFT SEVEN EIGHTHS BLOCK" },
            { "▊", "U+258A", "LEFT THREE QUARTERS BLOCK" },
            { "▋", "U+258B", "LEFT FIVE EIGHTHS BLOCK" },
            { "▌", "U+258C", "LEFT HALF BLOCK" },
            { "▍", "U+258D", "LEFT THREE EIGHTHS BLOCK" },
            { "▎", "U+258E", "LEFT ONE QUARTER BLOCK" },
            { "▏", "U+258F", "LEFT ONE EIGHTH BLOCK" },
            { "▐", "U+2590", "RIGHT HALF BLOCK" },
            { "░", "U+2591", "LIGHT SHADE" },
            { "▒", "U+2592", "MEDIUM SHADE" },
            { "▓", "U+2593", "DARK SHADE" },
            { "▔", "U+2594", "UPPER ONE EIGHTH BLOCK" },
            { "▕", "U+2595", "RIGHT ONE EIGHTH BLOCK" },
            { "▖", "U+2596", "QUADRANT LOWER LEFT" },
            { "▗", "U+2597", "QUADRANT LOWER RIGHT" },
            { "▘", "U+2598", "QUADRANT UPPER LEFT" },
            { "▙", "U+2599", "QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT" },
            { "▚", "U+259A", "QUADRANT UPPER LEFT AND LOWER RIGHT" },
            { "▛", "U+259B", "QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT" },
            { "▜", "U+259C", "QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT" },
            { "▝", "U+259D", "QUADRANT UPPER RIGHT" },
            { "▞", "U+259E", "QUADRANT UPPER RIGHT AND LOWER LEFT" },
            { "▟", "U+259F", "QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT" },
        },
    },
    {
        title        = "Geometric Shapes",
        unicodeRange = "U+25A0 - U+25FF",
        notes        = "Squares, circles, triangles, diamonds. Commonly used for UI markers.",
        entries = {
            { "■", "U+25A0", "BLACK SQUARE" },
            { "□", "U+25A1", "WHITE SQUARE" },
            { "▢", "U+25A2", "WHITE SQUARE WITH ROUNDED CORNERS" },
            { "▣", "U+25A3", "WHITE SQUARE CONTAINING BLACK SMALL SQUARE" },
            { "▤", "U+25A4", "SQUARE WITH HORIZONTAL FILL" },
            { "▥", "U+25A5", "SQUARE WITH VERTICAL FILL" },
            { "▦", "U+25A6", "SQUARE WITH ORTHOGONAL CROSSHATCH FILL" },
            { "▧", "U+25A7", "SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL" },
            { "▨", "U+25A8", "SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL" },
            { "▩", "U+25A9", "SQUARE WITH DIAGONAL CROSSHATCH FILL" },
            { "▪", "U+25AA", "BLACK SMALL SQUARE" },
            { "▫", "U+25AB", "WHITE SMALL SQUARE" },
            { "▬", "U+25AC", "BLACK RECTANGLE" },
            { "▭", "U+25AD", "WHITE RECTANGLE" },
            { "▮", "U+25AE", "BLACK VERTICAL RECTANGLE" },
            { "▯", "U+25AF", "WHITE VERTICAL RECTANGLE" },
            { "▰", "U+25B0", "BLACK PARALLELOGRAM" },
            { "▱", "U+25B1", "WHITE PARALLELOGRAM" },
            { "▲", "U+25B2", "BLACK UP-POINTING TRIANGLE" },
            { "△", "U+25B3", "WHITE UP-POINTING TRIANGLE" },
            { "▴", "U+25B4", "BLACK UP-POINTING SMALL TRIANGLE" },
            { "▵", "U+25B5", "WHITE UP-POINTING SMALL TRIANGLE" },
            { "▶", "U+25B6", "BLACK RIGHT-POINTING TRIANGLE" },
            { "▷", "U+25B7", "WHITE RIGHT-POINTING TRIANGLE" },
            { "▸", "U+25B8", "BLACK RIGHT-POINTING SMALL TRIANGLE" },
            { "▹", "U+25B9", "WHITE RIGHT-POINTING SMALL TRIANGLE" },
            { "►", "U+25BA", "BLACK RIGHT-POINTING POINTER" },
            { "▻", "U+25BB", "WHITE RIGHT-POINTING POINTER" },
            { "▼", "U+25BC", "BLACK DOWN-POINTING TRIANGLE" },
            { "▽", "U+25BD", "WHITE DOWN-POINTING TRIANGLE" },
            { "▾", "U+25BE", "BLACK DOWN-POINTING SMALL TRIANGLE" },
            { "▿", "U+25BF", "WHITE DOWN-POINTING SMALL TRIANGLE" },
            { "◀", "U+25C0", "BLACK LEFT-POINTING TRIANGLE" },
            { "◁", "U+25C1", "WHITE LEFT-POINTING TRIANGLE" },
            { "◂", "U+25C2", "BLACK LEFT-POINTING SMALL TRIANGLE" },
            { "◃", "U+25C3", "WHITE LEFT-POINTING SMALL TRIANGLE" },
            { "◄", "U+25C4", "BLACK LEFT-POINTING POINTER" },
            { "◅", "U+25C5", "WHITE LEFT-POINTING POINTER" },
            { "◆", "U+25C6", "BLACK DIAMOND" },
            { "◇", "U+25C7", "WHITE DIAMOND" },
            { "◈", "U+25C8", "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND" },
            { "◉", "U+25C9", "FISHEYE" },
            { "◊", "U+25CA", "LOZENGE" },
            { "○", "U+25CB", "WHITE CIRCLE" },
            { "◌", "U+25CC", "DOTTED CIRCLE" },
            { "◍", "U+25CD", "CIRCLE WITH VERTICAL FILL" },
            { "◎", "U+25CE", "BULLSEYE" },
            { "●", "U+25CF", "BLACK CIRCLE" },
            { "◐", "U+25D0", "CIRCLE WITH LEFT HALF BLACK" },
            { "◑", "U+25D1", "CIRCLE WITH RIGHT HALF BLACK" },
            { "◒", "U+25D2", "CIRCLE WITH LOWER HALF BLACK" },
            { "◓", "U+25D3", "CIRCLE WITH UPPER HALF BLACK" },
            { "◔", "U+25D4", "CIRCLE WITH UPPER RIGHT QUADRANT BLACK" },
            { "◕", "U+25D5", "CIRCLE WITH ALL BUT UPPER LEFT QUADRANT BLACK" },
            { "◖", "U+25D6", "LEFT HALF BLACK CIRCLE" },
            { "◗", "U+25D7", "RIGHT HALF BLACK CIRCLE" },
            { "◢", "U+25E2", "BLACK LOWER RIGHT TRIANGLE" },
            { "◣", "U+25E3", "BLACK LOWER LEFT TRIANGLE" },
            { "◤", "U+25E4", "BLACK UPPER LEFT TRIANGLE" },
            { "◥", "U+25E5", "BLACK UPPER RIGHT TRIANGLE" },
            { "◦", "U+25E6", "WHITE BULLET" },
            { "◯", "U+25EF", "LARGE CIRCLE" },
            { "◴", "U+25F4", "WHITE CIRCLE WITH UPPER LEFT QUADRANT" },
            { "◵", "U+25F5", "WHITE CIRCLE WITH LOWER LEFT QUADRANT" },
            { "◶", "U+25F6", "WHITE CIRCLE WITH LOWER RIGHT QUADRANT" },
            { "◷", "U+25F7", "WHITE CIRCLE WITH UPPER RIGHT QUADRANT" },
        },
    },
    {
        title        = "Box Drawing",
        unicodeRange = "U+2500 - U+257F",
        notes        = "Single and double lines, corners, tees. Essential for ASCII-art tables.",
        entries = {
            { "─", "U+2500", "BOX DRAWINGS LIGHT HORIZONTAL" },
            { "━", "U+2501", "BOX DRAWINGS HEAVY HORIZONTAL" },
            { "│", "U+2502", "BOX DRAWINGS LIGHT VERTICAL" },
            { "┃", "U+2503", "BOX DRAWINGS HEAVY VERTICAL" },
            { "┄", "U+2504", "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL" },
            { "┅", "U+2505", "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL" },
            { "┆", "U+2506", "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL" },
            { "┇", "U+2507", "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL" },
            { "┈", "U+2508", "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL" },
            { "┉", "U+2509", "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL" },
            { "┊", "U+250A", "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL" },
            { "┋", "U+250B", "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL" },
            { "┌", "U+250C", "BOX DRAWINGS LIGHT DOWN AND RIGHT" },
            { "┐", "U+2510", "BOX DRAWINGS LIGHT DOWN AND LEFT" },
            { "└", "U+2514", "BOX DRAWINGS LIGHT UP AND RIGHT" },
            { "┘", "U+2518", "BOX DRAWINGS LIGHT UP AND LEFT" },
            { "├", "U+251C", "BOX DRAWINGS LIGHT VERTICAL AND RIGHT" },
            { "┤", "U+2524", "BOX DRAWINGS LIGHT VERTICAL AND LEFT" },
            { "┬", "U+252C", "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL" },
            { "┴", "U+2534", "BOX DRAWINGS LIGHT UP AND HORIZONTAL" },
            { "┼", "U+253C", "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL" },
            { "╌", "U+254C", "BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL" },
            { "╍", "U+254D", "BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL" },
            { "╎", "U+254E", "BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL" },
            { "╏", "U+254F", "BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL" },
            { "═", "U+2550", "BOX DRAWINGS DOUBLE HORIZONTAL" },
            { "║", "U+2551", "BOX DRAWINGS DOUBLE VERTICAL" },
            { "╒", "U+2552", "BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE" },
            { "╓", "U+2553", "BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE" },
            { "╔", "U+2554", "BOX DRAWINGS DOUBLE DOWN AND RIGHT" },
            { "╕", "U+2555", "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE" },
            { "╖", "U+2556", "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE" },
            { "╗", "U+2557", "BOX DRAWINGS DOUBLE DOWN AND LEFT" },
            { "╘", "U+2558", "BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE" },
            { "╙", "U+2559", "BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE" },
            { "╚", "U+255A", "BOX DRAWINGS DOUBLE UP AND RIGHT" },
            { "╛", "U+255B", "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE" },
            { "╜", "U+255C", "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE" },
            { "╝", "U+255D", "BOX DRAWINGS DOUBLE UP AND LEFT" },
            { "╞", "U+255E", "BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE" },
            { "╟", "U+255F", "BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE" },
            { "╠", "U+2560", "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT" },
            { "╡", "U+2561", "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE" },
            { "╢", "U+2562", "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE" },
            { "╣", "U+2563", "BOX DRAWINGS DOUBLE VERTICAL AND LEFT" },
            { "╤", "U+2564", "BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE" },
            { "╥", "U+2565", "BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE" },
            { "╦", "U+2566", "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL" },
            { "╧", "U+2567", "BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE" },
            { "╨", "U+2568", "BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE" },
            { "╩", "U+2569", "BOX DRAWINGS DOUBLE UP AND HORIZONTAL" },
            { "╪", "U+256A", "BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE" },
            { "╫", "U+256B", "BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE" },
            { "╬", "U+256C", "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL" },
            { "╭", "U+256D", "BOX DRAWINGS LIGHT ARC DOWN AND RIGHT" },
            { "╮", "U+256E", "BOX DRAWINGS LIGHT ARC DOWN AND LEFT" },
            { "╯", "U+256F", "BOX DRAWINGS LIGHT ARC UP AND LEFT" },
            { "╰", "U+2570", "BOX DRAWINGS LIGHT ARC UP AND RIGHT" },
            { "╱", "U+2571", "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT" },
            { "╲", "U+2572", "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT" },
            { "╳", "U+2573", "BOX DRAWINGS LIGHT DIAGONAL CROSS" },
        },
    },
    {
        title        = "Arrows",
        unicodeRange = "U+2190 - U+21FF",
        notes        = "Basic arrows plus curved, double, and barbed variants.",
        entries = {
            { "←", "U+2190", "LEFTWARDS ARROW" },
            { "↑", "U+2191", "UPWARDS ARROW" },
            { "→", "U+2192", "RIGHTWARDS ARROW" },
            { "↓", "U+2193", "DOWNWARDS ARROW" },
            { "↔", "U+2194", "LEFT RIGHT ARROW" },
            { "↕", "U+2195", "UP DOWN ARROW" },
            { "↖", "U+2196", "NORTH WEST ARROW" },
            { "↗", "U+2197", "NORTH EAST ARROW" },
            { "↘", "U+2198", "SOUTH EAST ARROW" },
            { "↙", "U+2199", "SOUTH WEST ARROW" },
            { "↚", "U+219A", "LEFTWARDS ARROW WITH STROKE" },
            { "↛", "U+219B", "RIGHTWARDS ARROW WITH STROKE" },
            { "↜", "U+219C", "LEFTWARDS WAVE ARROW" },
            { "↝", "U+219D", "RIGHTWARDS WAVE ARROW" },
            { "↞", "U+219E", "LEFTWARDS TWO HEADED ARROW" },
            { "↟", "U+219F", "UPWARDS TWO HEADED ARROW" },
            { "↠", "U+21A0", "RIGHTWARDS TWO HEADED ARROW" },
            { "↡", "U+21A1", "DOWNWARDS TWO HEADED ARROW" },
            { "↢", "U+21A2", "LEFTWARDS ARROW WITH TAIL" },
            { "↣", "U+21A3", "RIGHTWARDS ARROW WITH TAIL" },
            { "↤", "U+21A4", "LEFTWARDS ARROW FROM BAR" },
            { "↥", "U+21A5", "UPWARDS ARROW FROM BAR" },
            { "↦", "U+21A6", "RIGHTWARDS ARROW FROM BAR" },
            { "↧", "U+21A7", "DOWNWARDS ARROW FROM BAR" },
            { "↩", "U+21A9", "LEFTWARDS ARROW WITH HOOK" },
            { "↪", "U+21AA", "RIGHTWARDS ARROW WITH HOOK" },
            { "↫", "U+21AB", "LEFTWARDS ARROW WITH LOOP" },
            { "↬", "U+21AC", "RIGHTWARDS ARROW WITH LOOP" },
            { "↭", "U+21AD", "LEFT RIGHT WAVE ARROW" },
            { "↮", "U+21AE", "LEFT RIGHT ARROW WITH STROKE" },
            { "↯", "U+21AF", "DOWNWARDS ZIGZAG ARROW" },
            { "↰", "U+21B0", "UPWARDS ARROW WITH TIP LEFTWARDS" },
            { "↱", "U+21B1", "UPWARDS ARROW WITH TIP RIGHTWARDS" },
            { "↲", "U+21B2", "DOWNWARDS ARROW WITH TIP LEFTWARDS" },
            { "↳", "U+21B3", "DOWNWARDS ARROW WITH TIP RIGHTWARDS" },
            { "↵", "U+21B5", "DOWNWARDS ARROW WITH CORNER LEFTWARDS" },
            { "↶", "U+21B6", "ANTICLOCKWISE TOP SEMICIRCLE ARROW" },
            { "↷", "U+21B7", "CLOCKWISE TOP SEMICIRCLE ARROW" },
            { "↺", "U+21BA", "ANTICLOCKWISE OPEN CIRCLE ARROW" },
            { "↻", "U+21BB", "CLOCKWISE OPEN CIRCLE ARROW" },
            { "⇄", "U+21C4", "RIGHTWARDS ARROW OVER LEFTWARDS ARROW" },
            { "⇅", "U+21C5", "UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW" },
            { "⇆", "U+21C6", "LEFTWARDS ARROW OVER RIGHTWARDS ARROW" },
            { "⇇", "U+21C7", "LEFTWARDS PAIRED ARROWS" },
            { "⇈", "U+21C8", "UPWARDS PAIRED ARROWS" },
            { "⇉", "U+21C9", "RIGHTWARDS PAIRED ARROWS" },
            { "⇊", "U+21CA", "DOWNWARDS PAIRED ARROWS" },
            { "⇐", "U+21D0", "LEFTWARDS DOUBLE ARROW" },
            { "⇑", "U+21D1", "UPWARDS DOUBLE ARROW" },
            { "⇒", "U+21D2", "RIGHTWARDS DOUBLE ARROW" },
            { "⇓", "U+21D3", "DOWNWARDS DOUBLE ARROW" },
            { "⇔", "U+21D4", "LEFT RIGHT DOUBLE ARROW" },
            { "⇕", "U+21D5", "UP DOWN DOUBLE ARROW" },
            { "⇖", "U+21D6", "NORTH WEST DOUBLE ARROW" },
            { "⇗", "U+21D7", "NORTH EAST DOUBLE ARROW" },
            { "⇘", "U+21D8", "SOUTH EAST DOUBLE ARROW" },
            { "⇙", "U+21D9", "SOUTH WEST DOUBLE ARROW" },
            { "⇚", "U+21DA", "LEFTWARDS TRIPLE ARROW" },
            { "⇛", "U+21DB", "RIGHTWARDS TRIPLE ARROW" },
            { "⇜", "U+21DC", "LEFTWARDS SQUIGGLE ARROW" },
            { "⇝", "U+21DD", "RIGHTWARDS SQUIGGLE ARROW" },
            { "⇠", "U+21E0", "LEFTWARDS DASHED ARROW" },
            { "⇡", "U+21E1", "UPWARDS DASHED ARROW" },
            { "⇢", "U+21E2", "RIGHTWARDS DASHED ARROW" },
            { "⇣", "U+21E3", "DOWNWARDS DASHED ARROW" },
            { "⇦", "U+21E6", "LEFTWARDS WHITE ARROW" },
            { "⇧", "U+21E7", "UPWARDS WHITE ARROW" },
            { "⇨", "U+21E8", "RIGHTWARDS WHITE ARROW" },
            { "⇩", "U+21E9", "DOWNWARDS WHITE ARROW" },
        },
    },
    {
        title        = "Miscellaneous Symbols",
        unicodeRange = "U+2600 - U+26FF",
        notes        = "Stars, weather, card suits, warning signs, music notes. Mixed font support.",
        entries = {
            { "☀", "U+2600", "BLACK SUN WITH RAYS" },
            { "☁", "U+2601", "CLOUD" },
            { "☂", "U+2602", "UMBRELLA" },
            { "☃", "U+2603", "SNOWMAN" },
            { "☄", "U+2604", "COMET" },
            { "★", "U+2605", "BLACK STAR" },
            { "☆", "U+2606", "WHITE STAR" },
            { "☇", "U+2607", "LIGHTNING" },
            { "☈", "U+2608", "THUNDERSTORM" },
            { "☉", "U+2609", "SUN" },
            { "☎", "U+260E", "BLACK TELEPHONE" },
            { "☏", "U+260F", "WHITE TELEPHONE" },
            { "☐", "U+2610", "BALLOT BOX" },
            { "☑", "U+2611", "BALLOT BOX WITH CHECK" },
            { "☒", "U+2612", "BALLOT BOX WITH X" },
            { "☓", "U+2613", "SALTIRE" },
            { "☔", "U+2614", "UMBRELLA WITH RAIN DROPS" },
            { "☕", "U+2615", "HOT BEVERAGE" },
            { "☘", "U+2618", "SHAMROCK" },
            { "☚", "U+261A", "BLACK LEFT POINTING INDEX" },
            { "☛", "U+261B", "BLACK RIGHT POINTING INDEX" },
            { "☜", "U+261C", "WHITE LEFT POINTING INDEX" },
            { "☝", "U+261D", "WHITE UP POINTING INDEX" },
            { "☞", "U+261E", "WHITE RIGHT POINTING INDEX" },
            { "☟", "U+261F", "WHITE DOWN POINTING INDEX" },
            { "☠", "U+2620", "SKULL AND CROSSBONES" },
            { "☡", "U+2621", "CAUTION SIGN" },
            { "☢", "U+2622", "RADIOACTIVE SIGN" },
            { "☣", "U+2623", "BIOHAZARD SIGN" },
            { "☤", "U+2624", "CADUCEUS" },
            { "☥", "U+2625", "ANKH" },
            { "☦", "U+2626", "ORTHODOX CROSS" },
            { "☮", "U+262E", "PEACE SYMBOL" },
            { "☯", "U+262F", "YIN YANG" },
            { "☸", "U+2638", "WHEEL OF DHARMA" },
            { "☹", "U+2639", "WHITE FROWNING FACE" },
            { "☺", "U+263A", "WHITE SMILING FACE" },
            { "☻", "U+263B", "BLACK SMILING FACE" },
            { "☼", "U+263C", "WHITE SUN WITH RAYS" },
            { "☽", "U+263D", "FIRST QUARTER MOON" },
            { "☾", "U+263E", "LAST QUARTER MOON" },
            { "♀", "U+2640", "FEMALE SIGN" },
            { "♂", "U+2642", "MALE SIGN" },
            { "♠", "U+2660", "BLACK SPADE SUIT" },
            { "♡", "U+2661", "WHITE HEART SUIT" },
            { "♢", "U+2662", "WHITE DIAMOND SUIT" },
            { "♣", "U+2663", "BLACK CLUB SUIT" },
            { "♤", "U+2664", "WHITE SPADE SUIT" },
            { "♥", "U+2665", "BLACK HEART SUIT" },
            { "♦", "U+2666", "BLACK DIAMOND SUIT" },
            { "♧", "U+2667", "WHITE CLUB SUIT" },
            { "♩", "U+2669", "QUARTER NOTE" },
            { "♪", "U+266A", "EIGHTH NOTE" },
            { "♫", "U+266B", "BEAMED EIGHTH NOTES" },
            { "♬", "U+266C", "BEAMED SIXTEENTH NOTES" },
            { "♭", "U+266D", "MUSIC FLAT SIGN" },
            { "♮", "U+266E", "MUSIC NATURAL SIGN" },
            { "♯", "U+266F", "MUSIC SHARP SIGN" },
            { "⚐", "U+2690", "WHITE FLAG" },
            { "⚑", "U+2691", "BLACK FLAG" },
            { "⚒", "U+2692", "HAMMER AND PICK" },
            { "⚓", "U+2693", "ANCHOR" },
            { "⚔", "U+2694", "CROSSED SWORDS" },
            { "⚕", "U+2695", "STAFF OF AESCULAPIUS" },
            { "⚖", "U+2696", "SCALES" },
            { "⚗", "U+2697", "ALEMBIC" },
            { "⚘", "U+2698", "FLOWER" },
            { "⚙", "U+2699", "GEAR" },
            { "⚛", "U+269B", "ATOM SYMBOL" },
            { "⚠", "U+26A0", "WARNING SIGN" },
            { "⚡", "U+26A1", "HIGH VOLTAGE SIGN" },
            { "⚪", "U+26AA", "MEDIUM WHITE CIRCLE" },
            { "⚫", "U+26AB", "MEDIUM BLACK CIRCLE" },
            { "⚰", "U+26B0", "COFFIN" },
            { "⚱", "U+26B1", "FUNERAL URN" },
            { "⚽", "U+26BD", "SOCCER BALL" },
            { "⚾", "U+26BE", "BASEBALL" },
            { "⛄", "U+26C4", "SNOWMAN WITHOUT SNOW" },
            { "⛅", "U+26C5", "SUN BEHIND CLOUD" },
            { "⛔", "U+26D4", "NO ENTRY" },
            { "⛪", "U+26EA", "CHURCH" },
            { "⛰", "U+26F0", "MOUNTAIN" },
            { "⛱", "U+26F1", "UMBRELLA ON GROUND" },
            { "⛲", "U+26F2", "FOUNTAIN" },
            { "⛳", "U+26F3", "FLAG IN HOLE" },
            { "⛵", "U+26F5", "SAILBOAT" },
            { "⛺", "U+26FA", "TENT" },
            { "⛽", "U+26FD", "FUEL PUMP" },
        },
    },
    {
        title        = "Dingbats",
        unicodeRange = "U+2700 - U+27BF",
        notes        = "Checkmarks, crosses, decorative symbols. Often emoji-rendered.",
        entries = {
            { "✁", "U+2701", "UPPER BLADE SCISSORS" },
            { "✂", "U+2702", "BLACK SCISSORS" },
            { "✃", "U+2703", "LOWER BLADE SCISSORS" },
            { "✄", "U+2704", "WHITE SCISSORS" },
            { "✆", "U+2706", "TELEPHONE LOCATION SIGN" },
            { "✇", "U+2707", "TAPE DRIVE" },
            { "✈", "U+2708", "AIRPLANE" },
            { "✉", "U+2709", "ENVELOPE" },
            { "✊", "U+270A", "RAISED FIST" },
            { "✋", "U+270B", "RAISED HAND" },
            { "✌", "U+270C", "VICTORY HAND" },
            { "✍", "U+270D", "WRITING HAND" },
            { "✎", "U+270E", "LOWER RIGHT PENCIL" },
            { "✏", "U+270F", "PENCIL" },
            { "✐", "U+2710", "UPPER RIGHT PENCIL" },
            { "✑", "U+2711", "WHITE NIB" },
            { "✒", "U+2712", "BLACK NIB" },
            { "✓", "U+2713", "CHECK MARK" },
            { "✔", "U+2714", "HEAVY CHECK MARK" },
            { "✕", "U+2715", "MULTIPLICATION X" },
            { "✖", "U+2716", "HEAVY MULTIPLICATION X" },
            { "✗", "U+2717", "BALLOT X" },
            { "✘", "U+2718", "HEAVY BALLOT X" },
            { "✙", "U+2719", "OUTLINED GREEK CROSS" },
            { "✚", "U+271A", "HEAVY GREEK CROSS" },
            { "✛", "U+271B", "OPEN CENTRE CROSS" },
            { "✜", "U+271C", "HEAVY OPEN CENTRE CROSS" },
            { "✝", "U+271D", "LATIN CROSS" },
            { "✞", "U+271E", "SHADOWED WHITE LATIN CROSS" },
            { "✟", "U+271F", "OUTLINED LATIN CROSS" },
            { "✠", "U+2720", "MALTESE CROSS" },
            { "✡", "U+2721", "STAR OF DAVID" },
            { "✦", "U+2726", "BLACK FOUR POINTED STAR" },
            { "✧", "U+2727", "WHITE FOUR POINTED STAR" },
            { "✩", "U+2729", "STRESS OUTLINED WHITE STAR" },
            { "✪", "U+272A", "CIRCLED WHITE STAR" },
            { "✫", "U+272B", "OPEN CENTRE BLACK STAR" },
            { "✬", "U+272C", "BLACK CENTRE WHITE STAR" },
            { "✭", "U+272D", "OUTLINED BLACK STAR" },
            { "✮", "U+272E", "HEAVY OUTLINED BLACK STAR" },
            { "✯", "U+272F", "PINWHEEL STAR" },
            { "✰", "U+2730", "SHADOWED WHITE STAR" },
            { "✱", "U+2731", "HEAVY ASTERISK" },
            { "✲", "U+2732", "OPEN CENTRE ASTERISK" },
            { "✳", "U+2733", "EIGHT SPOKED ASTERISK" },
            { "✴", "U+2734", "EIGHT POINTED BLACK STAR" },
            { "✵", "U+2735", "EIGHT POINTED PINWHEEL STAR" },
            { "✶", "U+2736", "SIX POINTED BLACK STAR" },
            { "✷", "U+2737", "EIGHT POINTED RECTILINEAR BLACK STAR" },
            { "✸", "U+2738", "HEAVY EIGHT POINTED RECTILINEAR BLACK STAR" },
            { "✹", "U+2739", "TWELVE POINTED BLACK STAR" },
            { "✺", "U+273A", "SIXTEEN POINTED ASTERISK" },
            { "✻", "U+273B", "TEARDROP-SPOKED ASTERISK" },
            { "✽", "U+273D", "HEAVY TEARDROP-SPOKED ASTERISK" },
            { "✾", "U+273E", "SIX PETALLED BLACK AND WHITE FLORETTE" },
            { "✿", "U+273F", "BLACK FLORETTE" },
            { "❀", "U+2740", "WHITE FLORETTE" },
            { "❁", "U+2741", "EIGHT PETALLED OUTLINED BLACK FLORETTE" },
            { "❂", "U+2742", "CIRCLED OPEN CENTRE EIGHT POINTED STAR" },
            { "❄", "U+2744", "SNOWFLAKE" },
            { "❅", "U+2745", "TIGHT TRIFOLIATE SNOWFLAKE" },
            { "❆", "U+2746", "HEAVY CHEVRON SNOWFLAKE" },
            { "❇", "U+2747", "SPARKLE" },
            { "❈", "U+2748", "HEAVY SPARKLE" },
            { "❉", "U+2749", "BALLOON-SPOKED ASTERISK" },
            { "❊", "U+274A", "EIGHT TEARDROP-SPOKED PROPELLER ASTERISK" },
            { "❋", "U+274B", "HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK" },
            { "❍", "U+274D", "SHADOWED WHITE CIRCLE" },
            { "❏", "U+274F", "LOWER RIGHT DROP-SHADOWED WHITE SQUARE" },
            { "❐", "U+2750", "UPPER RIGHT DROP-SHADOWED WHITE SQUARE" },
            { "❑", "U+2751", "LOWER RIGHT SHADOWED WHITE SQUARE" },
            { "❒", "U+2752", "UPPER RIGHT SHADOWED WHITE SQUARE" },
            { "❖", "U+2756", "BLACK DIAMOND MINUS WHITE X" },
            { "❘", "U+2758", "LIGHT VERTICAL BAR" },
            { "❙", "U+2759", "MEDIUM VERTICAL BAR" },
            { "❚", "U+275A", "HEAVY VERTICAL BAR" },
            { "❛", "U+275B", "HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT" },
            { "❜", "U+275C", "HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT" },
            { "❝", "U+275D", "HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT" },
            { "❞", "U+275E", "HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT" },
            { "❣", "U+2763", "HEAVY HEART EXCLAMATION MARK ORNAMENT" },
            { "❤", "U+2764", "HEAVY BLACK HEART" },
            { "❥", "U+2765", "ROTATED HEAVY BLACK HEART BULLET" },
            { "❦", "U+2766", "FLORAL HEART" },
            { "❧", "U+2767", "ROTATED FLORAL HEART BULLET" },
            { "➔", "U+2794", "HEAVY WIDE-HEADED RIGHTWARDS ARROW" },
            { "➕", "U+2795", "HEAVY PLUS SIGN" },
            { "➖", "U+2796", "HEAVY MINUS SIGN" },
            { "➗", "U+2797", "HEAVY DIVISION SIGN" },
            { "➜", "U+279C", "HEAVY ROUND-TIPPED RIGHTWARDS ARROW" },
            { "➡", "U+27A1", "BLACK RIGHTWARDS ARROW" },
            { "➤", "U+27A4", "BLACK RIGHTWARDS ARROWHEAD" },
            { "➥", "U+27A5", "HEAVY BLACK CURVED DOWNWARDS AND RIGHTWARDS ARROW" },
            { "➦", "U+27A6", "HEAVY BLACK CURVED UPWARDS AND RIGHTWARDS ARROW" },
            { "➰", "U+27B0", "CURLY LOOP" },
            { "➿", "U+27BF", "DOUBLE CURLY LOOP" },
        },
    },
    {
        title        = "Mathematical Operators",
        unicodeRange = "U+2200 - U+22FF",
        notes        = "Major operators only: sums, integrals, comparisons, logic.",
        entries = {
            { "∀", "U+2200", "FOR ALL" },
            { "∂", "U+2202", "PARTIAL DIFFERENTIAL" },
            { "∃", "U+2203", "THERE EXISTS" },
            { "∄", "U+2204", "THERE DOES NOT EXIST" },
            { "∅", "U+2205", "EMPTY SET" },
            { "∆", "U+2206", "INCREMENT" },
            { "∇", "U+2207", "NABLA" },
            { "∈", "U+2208", "ELEMENT OF" },
            { "∉", "U+2209", "NOT AN ELEMENT OF" },
            { "∋", "U+220B", "CONTAINS AS MEMBER" },
            { "∌", "U+220C", "DOES NOT CONTAIN AS MEMBER" },
            { "∏", "U+220F", "N-ARY PRODUCT" },
            { "∑", "U+2211", "N-ARY SUMMATION" },
            { "−", "U+2212", "MINUS SIGN" },
            { "∓", "U+2213", "MINUS-OR-PLUS SIGN" },
            { "∔", "U+2214", "DOT PLUS" },
            { "∕", "U+2215", "DIVISION SLASH" },
            { "∖", "U+2216", "SET MINUS" },
            { "∗", "U+2217", "ASTERISK OPERATOR" },
            { "∘", "U+2218", "RING OPERATOR" },
            { "∙", "U+2219", "BULLET OPERATOR" },
            { "√", "U+221A", "SQUARE ROOT" },
            { "∛", "U+221B", "CUBE ROOT" },
            { "∜", "U+221C", "FOURTH ROOT" },
            { "∝", "U+221D", "PROPORTIONAL TO" },
            { "∞", "U+221E", "INFINITY" },
            { "∠", "U+2220", "ANGLE" },
            { "∡", "U+2221", "MEASURED ANGLE" },
            { "∢", "U+2222", "SPHERICAL ANGLE" },
            { "∣", "U+2223", "DIVIDES" },
            { "∥", "U+2225", "PARALLEL TO" },
            { "∧", "U+2227", "LOGICAL AND" },
            { "∨", "U+2228", "LOGICAL OR" },
            { "∩", "U+2229", "INTERSECTION" },
            { "∪", "U+222A", "UNION" },
            { "∫", "U+222B", "INTEGRAL" },
            { "∬", "U+222C", "DOUBLE INTEGRAL" },
            { "∭", "U+222D", "TRIPLE INTEGRAL" },
            { "∮", "U+222E", "CONTOUR INTEGRAL" },
            { "∴", "U+2234", "THEREFORE" },
            { "∵", "U+2235", "BECAUSE" },
            { "∶", "U+2236", "RATIO" },
            { "∷", "U+2237", "PROPORTION" },
            { "∼", "U+223C", "TILDE OPERATOR" },
            { "∽", "U+223D", "REVERSED TILDE" },
            { "≅", "U+2245", "APPROXIMATELY EQUAL TO" },
            { "≈", "U+2248", "ALMOST EQUAL TO" },
            { "≉", "U+2249", "NOT ALMOST EQUAL TO" },
            { "≠", "U+2260", "NOT EQUAL TO" },
            { "≡", "U+2261", "IDENTICAL TO" },
            { "≢", "U+2262", "NOT IDENTICAL TO" },
            { "≤", "U+2264", "LESS-THAN OR EQUAL TO" },
            { "≥", "U+2265", "GREATER-THAN OR EQUAL TO" },
            { "≪", "U+226A", "MUCH LESS-THAN" },
            { "≫", "U+226B", "MUCH GREATER-THAN" },
            { "⊂", "U+2282", "SUBSET OF" },
            { "⊃", "U+2283", "SUPERSET OF" },
            { "⊄", "U+2284", "NOT A SUBSET OF" },
            { "⊆", "U+2286", "SUBSET OF OR EQUAL TO" },
            { "⊇", "U+2287", "SUPERSET OF OR EQUAL TO" },
            { "⊕", "U+2295", "CIRCLED PLUS" },
            { "⊖", "U+2296", "CIRCLED MINUS" },
            { "⊗", "U+2297", "CIRCLED TIMES" },
            { "⊘", "U+2298", "CIRCLED DIVISION SLASH" },
            { "⊙", "U+2299", "CIRCLED DOT OPERATOR" },
            { "⊥", "U+22A5", "UP TACK" },
            { "⋅", "U+22C5", "DOT OPERATOR" },
            { "⋆", "U+22C6", "STAR OPERATOR" },
            { "⋮", "U+22EE", "VERTICAL ELLIPSIS" },
            { "⋯", "U+22EF", "MIDLINE HORIZONTAL ELLIPSIS" },
            { "⋰", "U+22F0", "UP RIGHT DIAGONAL ELLIPSIS" },
            { "⋱", "U+22F1", "DOWN RIGHT DIAGONAL ELLIPSIS" },
        },
    },
    {
        title        = "Miscellaneous Technical",
        unicodeRange = "U+2300 - U+23FF",
        notes        = "Keyboard symbols, return, scissors, brackets.",
        entries = {
            { "⌀", "U+2300", "DIAMETER SIGN" },
            { "⌂", "U+2302", "HOUSE" },
            { "⌃", "U+2303", "UP ARROWHEAD (CONTROL)" },
            { "⌄", "U+2304", "DOWN ARROWHEAD" },
            { "⌅", "U+2305", "PROJECTIVE" },
            { "⌆", "U+2306", "PERSPECTIVE" },
            { "⌇", "U+2307", "WAVY LINE" },
            { "⌘", "U+2318", "PLACE OF INTEREST SIGN (COMMAND)" },
            { "⌙", "U+2319", "TURNED NOT SIGN" },
            { "⌚", "U+231A", "WATCH" },
            { "⌛", "U+231B", "HOURGLASS" },
            { "⌥", "U+2325", "OPTION KEY" },
            { "⌦", "U+2326", "ERASE TO THE RIGHT" },
            { "⌧", "U+2327", "X IN A RECTANGLE BOX" },
            { "⌨", "U+2328", "KEYBOARD" },
            { "⌫", "U+232B", "ERASE TO THE LEFT" },
            { "⌬", "U+232C", "BENZENE RING" },
            { "⍻", "U+237B", "NOT CHECK MARK" },
            { "⎈", "U+2388", "HELM SYMBOL" },
            { "⏎", "U+23CE", "RETURN SYMBOL" },
            { "⏏", "U+23CF", "EJECT SYMBOL" },
            { "⏚", "U+23DA", "EARTH GROUND" },
            { "⏩", "U+23E9", "BLACK RIGHT-POINTING DOUBLE TRIANGLE" },
            { "⏪", "U+23EA", "BLACK LEFT-POINTING DOUBLE TRIANGLE" },
            { "⏫", "U+23EB", "BLACK UP-POINTING DOUBLE TRIANGLE" },
            { "⏬", "U+23EC", "BLACK DOWN-POINTING DOUBLE TRIANGLE" },
            { "⏭", "U+23ED", "BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR" },
            { "⏮", "U+23EE", "BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR" },
            { "⏯", "U+23EF", "BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR" },
            { "⏰", "U+23F0", "ALARM CLOCK" },
            { "⏱", "U+23F1", "STOPWATCH" },
            { "⏲", "U+23F2", "TIMER CLOCK" },
            { "⏳", "U+23F3", "HOURGLASS WITH FLOWING SAND" },
            { "⏴", "U+23F4", "BLACK MEDIUM LEFT-POINTING TRIANGLE" },
            { "⏵", "U+23F5", "BLACK MEDIUM RIGHT-POINTING TRIANGLE" },
            { "⏶", "U+23F6", "BLACK MEDIUM UP-POINTING TRIANGLE" },
            { "⏷", "U+23F7", "BLACK MEDIUM DOWN-POINTING TRIANGLE" },
            { "⏸", "U+23F8", "DOUBLE VERTICAL BAR" },
            { "⏹", "U+23F9", "BLACK SQUARE FOR STOP" },
            { "⏺", "U+23FA", "BLACK CIRCLE FOR RECORD" },
        },
    },
    {
        title        = "General Punctuation Extras",
        unicodeRange = "U+2000 - U+206F",
        notes        = "Em-dash, en-dash, ellipsis, bullets, daggers, special spaces.",
        entries = {
            { "‐", "U+2010", "HYPHEN" },
            { "‑", "U+2011", "NON-BREAKING HYPHEN" },
            { "‒", "U+2012", "FIGURE DASH" },
            { "–", "U+2013", "EN DASH" },
            { "—", "U+2014", "EM DASH" },
            { "―", "U+2015", "HORIZONTAL BAR" },
            { "‖", "U+2016", "DOUBLE VERTICAL LINE" },
            { "‗", "U+2017", "DOUBLE LOW LINE" },
            { "‘", "U+2018", "LEFT SINGLE QUOTATION MARK" },
            { "’", "U+2019", "RIGHT SINGLE QUOTATION MARK" },
            { "‚", "U+201A", "SINGLE LOW-9 QUOTATION MARK" },
            { "‛", "U+201B", "SINGLE HIGH-REVERSED-9 QUOTATION MARK" },
            { "“", "U+201C", "LEFT DOUBLE QUOTATION MARK" },
            { "”", "U+201D", "RIGHT DOUBLE QUOTATION MARK" },
            { "„", "U+201E", "DOUBLE LOW-9 QUOTATION MARK" },
            { "‟", "U+201F", "DOUBLE HIGH-REVERSED-9 QUOTATION MARK" },
            { "†", "U+2020", "DAGGER" },
            { "‡", "U+2021", "DOUBLE DAGGER" },
            { "•", "U+2022", "BULLET" },
            { "‣", "U+2023", "TRIANGULAR BULLET" },
            { "․", "U+2024", "ONE DOT LEADER" },
            { "‥", "U+2025", "TWO DOT LEADER" },
            { "…", "U+2026", "HORIZONTAL ELLIPSIS" },
            { "‧", "U+2027", "HYPHENATION POINT" },
            { "‰", "U+2030", "PER MILLE SIGN" },
            { "‱", "U+2031", "PER TEN THOUSAND SIGN" },
            { "′", "U+2032", "PRIME" },
            { "″", "U+2033", "DOUBLE PRIME" },
            { "‴", "U+2034", "TRIPLE PRIME" },
            { "‵", "U+2035", "REVERSED PRIME" },
            { "‹", "U+2039", "SINGLE LEFT-POINTING ANGLE QUOTATION MARK" },
            { "›", "U+203A", "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK" },
            { "※", "U+203B", "REFERENCE MARK" },
            { "‼", "U+203C", "DOUBLE EXCLAMATION MARK" },
            { "‽", "U+203D", "INTERROBANG" },
            { "‾", "U+203E", "OVERLINE" },
            { "⁂", "U+2042", "ASTERISM" },
            { "⁃", "U+2043", "HYPHEN BULLET" },
            { "⁄", "U+2044", "FRACTION SLASH" },
            { "⁇", "U+2047", "DOUBLE QUESTION MARK" },
            { "⁈", "U+2048", "QUESTION EXCLAMATION MARK" },
            { "⁉", "U+2049", "EXCLAMATION QUESTION MARK" },
            { "⁋", "U+204B", "REVERSED PILCROW SIGN" },
            { "⁌", "U+204C", "BLACK LEFTWARDS BULLET" },
            { "⁍", "U+204D", "BLACK RIGHTWARDS BULLET" },
            { "⁎", "U+204E", "LOW ASTERISK" },
        },
    },
    {
        title        = "Letterlike Symbols",
        unicodeRange = "U+2100 - U+214F",
        notes        = "Common: TM, copyright, degree, ohm, Numero.",
        entries = {
            { "℀", "U+2100", "ACCOUNT OF" },
            { "℁", "U+2101", "ADDRESSED TO THE SUBJECT" },
            { "ℂ", "U+2102", "DOUBLE-STRUCK CAPITAL C" },
            { "℃", "U+2103", "DEGREE CELSIUS" },
            { "℅", "U+2105", "CARE OF" },
            { "℆", "U+2106", "CADA UNA" },
            { "℉", "U+2109", "DEGREE FAHRENHEIT" },
            { "ℊ", "U+210A", "SCRIPT SMALL G" },
            { "ℋ", "U+210B", "SCRIPT CAPITAL H" },
            { "ℌ", "U+210C", "BLACK-LETTER CAPITAL H" },
            { "ℍ", "U+210D", "DOUBLE-STRUCK CAPITAL H" },
            { "ℎ", "U+210E", "PLANCK CONSTANT" },
            { "ℏ", "U+210F", "PLANCK CONSTANT OVER TWO PI" },
            { "ℐ", "U+2110", "SCRIPT CAPITAL I" },
            { "ℑ", "U+2111", "BLACK-LETTER CAPITAL I" },
            { "ℒ", "U+2112", "SCRIPT CAPITAL L" },
            { "ℓ", "U+2113", "SCRIPT SMALL L" },
            { "ℕ", "U+2115", "DOUBLE-STRUCK CAPITAL N" },
            { "№", "U+2116", "NUMERO SIGN" },
            { "℗", "U+2117", "SOUND RECORDING COPYRIGHT" },
            { "℘", "U+2118", "SCRIPT CAPITAL P" },
            { "ℙ", "U+2119", "DOUBLE-STRUCK CAPITAL P" },
            { "ℚ", "U+211A", "DOUBLE-STRUCK CAPITAL Q" },
            { "ℛ", "U+211B", "SCRIPT CAPITAL R" },
            { "ℜ", "U+211C", "BLACK-LETTER CAPITAL R" },
            { "ℝ", "U+211D", "DOUBLE-STRUCK CAPITAL R" },
            { "℞", "U+211E", "PRESCRIPTION TAKE" },
            { "℠", "U+2120", "SERVICE MARK" },
            { "℡", "U+2121", "TELEPHONE SIGN" },
            { "™", "U+2122", "TRADE MARK SIGN" },
            { "℣", "U+2123", "VERSICLE" },
            { "ℤ", "U+2124", "DOUBLE-STRUCK CAPITAL Z" },
            { "℥", "U+2125", "OUNCE SIGN" },
            { "Ω", "U+2126", "OHM SIGN" },
            { "℧", "U+2127", "INVERTED OHM SIGN" },
            { "ℨ", "U+2128", "BLACK-LETTER CAPITAL Z" },
            { "Å", "U+212B", "ANGSTROM SIGN" },
            { "ℬ", "U+212C", "SCRIPT CAPITAL B" },
            { "ℭ", "U+212D", "BLACK-LETTER CAPITAL C" },
            { "℮", "U+212E", "ESTIMATED SYMBOL" },
            { "ℯ", "U+212F", "SCRIPT SMALL E" },
            { "ℰ", "U+2130", "SCRIPT CAPITAL E" },
            { "ℱ", "U+2131", "SCRIPT CAPITAL F" },
            { "ℳ", "U+2133", "SCRIPT CAPITAL M" },
            { "ℴ", "U+2134", "SCRIPT SMALL O" },
            { "ℵ", "U+2135", "ALEF SYMBOL" },
            { "ℶ", "U+2136", "BET SYMBOL" },
            { "ℷ", "U+2137", "GIMEL SYMBOL" },
            { "ℸ", "U+2138", "DALET SYMBOL" },
        },
    },
    {
        title        = "Number Forms / Roman Numerals",
        unicodeRange = "U+2150 - U+218F",
        notes        = "Vulgar fractions, Roman numerals (upper and lower case).",
        entries = {
            { "⅐", "U+2150", "VULGAR FRACTION ONE SEVENTH" },
            { "⅑", "U+2151", "VULGAR FRACTION ONE NINTH" },
            { "⅒", "U+2152", "VULGAR FRACTION ONE TENTH" },
            { "⅓", "U+2153", "VULGAR FRACTION ONE THIRD" },
            { "⅔", "U+2154", "VULGAR FRACTION TWO THIRDS" },
            { "⅕", "U+2155", "VULGAR FRACTION ONE FIFTH" },
            { "⅖", "U+2156", "VULGAR FRACTION TWO FIFTHS" },
            { "⅗", "U+2157", "VULGAR FRACTION THREE FIFTHS" },
            { "⅘", "U+2158", "VULGAR FRACTION FOUR FIFTHS" },
            { "⅙", "U+2159", "VULGAR FRACTION ONE SIXTH" },
            { "⅚", "U+215A", "VULGAR FRACTION FIVE SIXTHS" },
            { "⅛", "U+215B", "VULGAR FRACTION ONE EIGHTH" },
            { "⅜", "U+215C", "VULGAR FRACTION THREE EIGHTHS" },
            { "⅝", "U+215D", "VULGAR FRACTION FIVE EIGHTHS" },
            { "⅞", "U+215E", "VULGAR FRACTION SEVEN EIGHTHS" },
            { "⅟", "U+215F", "FRACTION NUMERATOR ONE" },
            { "Ⅰ", "U+2160", "ROMAN NUMERAL ONE" },
            { "Ⅱ", "U+2161", "ROMAN NUMERAL TWO" },
            { "Ⅲ", "U+2162", "ROMAN NUMERAL THREE" },
            { "Ⅳ", "U+2163", "ROMAN NUMERAL FOUR" },
            { "Ⅴ", "U+2164", "ROMAN NUMERAL FIVE" },
            { "Ⅵ", "U+2165", "ROMAN NUMERAL SIX" },
            { "Ⅶ", "U+2166", "ROMAN NUMERAL SEVEN" },
            { "Ⅷ", "U+2167", "ROMAN NUMERAL EIGHT" },
            { "Ⅸ", "U+2168", "ROMAN NUMERAL NINE" },
            { "Ⅹ", "U+2169", "ROMAN NUMERAL TEN" },
            { "Ⅺ", "U+216A", "ROMAN NUMERAL ELEVEN" },
            { "Ⅻ", "U+216B", "ROMAN NUMERAL TWELVE" },
            { "Ⅼ", "U+216C", "ROMAN NUMERAL FIFTY" },
            { "Ⅽ", "U+216D", "ROMAN NUMERAL ONE HUNDRED" },
            { "Ⅾ", "U+216E", "ROMAN NUMERAL FIVE HUNDRED" },
            { "Ⅿ", "U+216F", "ROMAN NUMERAL ONE THOUSAND" },
            { "ⅰ", "U+2170", "SMALL ROMAN NUMERAL ONE" },
            { "ⅱ", "U+2171", "SMALL ROMAN NUMERAL TWO" },
            { "ⅲ", "U+2172", "SMALL ROMAN NUMERAL THREE" },
            { "ⅳ", "U+2173", "SMALL ROMAN NUMERAL FOUR" },
            { "ⅴ", "U+2174", "SMALL ROMAN NUMERAL FIVE" },
            { "ⅵ", "U+2175", "SMALL ROMAN NUMERAL SIX" },
            { "ⅶ", "U+2176", "SMALL ROMAN NUMERAL SEVEN" },
            { "ⅷ", "U+2177", "SMALL ROMAN NUMERAL EIGHT" },
            { "ⅸ", "U+2178", "SMALL ROMAN NUMERAL NINE" },
            { "ⅹ", "U+2179", "SMALL ROMAN NUMERAL TEN" },
            { "ⅺ", "U+217A", "SMALL ROMAN NUMERAL ELEVEN" },
            { "ⅻ", "U+217B", "SMALL ROMAN NUMERAL TWELVE" },
            { "ⅼ", "U+217C", "SMALL ROMAN NUMERAL FIFTY" },
            { "ⅽ", "U+217D", "SMALL ROMAN NUMERAL ONE HUNDRED" },
            { "ⅾ", "U+217E", "SMALL ROMAN NUMERAL FIVE HUNDRED" },
            { "ⅿ", "U+217F", "SMALL ROMAN NUMERAL ONE THOUSAND" },
        },
    },
    {
        title        = "Superscripts and Subscripts",
        unicodeRange = "U+2070 - U+209F",
        notes        = "Digits and selected letters in super/subscript form.",
        entries = {
            { "⁰", "U+2070", "SUPERSCRIPT ZERO" },
            { "ⁱ", "U+2071", "SUPERSCRIPT LATIN SMALL LETTER I" },
            { "⁴", "U+2074", "SUPERSCRIPT FOUR" },
            { "⁵", "U+2075", "SUPERSCRIPT FIVE" },
            { "⁶", "U+2076", "SUPERSCRIPT SIX" },
            { "⁷", "U+2077", "SUPERSCRIPT SEVEN" },
            { "⁸", "U+2078", "SUPERSCRIPT EIGHT" },
            { "⁹", "U+2079", "SUPERSCRIPT NINE" },
            { "⁺", "U+207A", "SUPERSCRIPT PLUS SIGN" },
            { "⁻", "U+207B", "SUPERSCRIPT MINUS" },
            { "⁼", "U+207C", "SUPERSCRIPT EQUALS SIGN" },
            { "⁽", "U+207D", "SUPERSCRIPT LEFT PARENTHESIS" },
            { "⁾", "U+207E", "SUPERSCRIPT RIGHT PARENTHESIS" },
            { "ⁿ", "U+207F", "SUPERSCRIPT LATIN SMALL LETTER N" },
            { "₀", "U+2080", "SUBSCRIPT ZERO" },
            { "₁", "U+2081", "SUBSCRIPT ONE" },
            { "₂", "U+2082", "SUBSCRIPT TWO" },
            { "₃", "U+2083", "SUBSCRIPT THREE" },
            { "₄", "U+2084", "SUBSCRIPT FOUR" },
            { "₅", "U+2085", "SUBSCRIPT FIVE" },
            { "₆", "U+2086", "SUBSCRIPT SIX" },
            { "₇", "U+2087", "SUBSCRIPT SEVEN" },
            { "₈", "U+2088", "SUBSCRIPT EIGHT" },
            { "₉", "U+2089", "SUBSCRIPT NINE" },
            { "₊", "U+208A", "SUBSCRIPT PLUS SIGN" },
            { "₋", "U+208B", "SUBSCRIPT MINUS" },
            { "₌", "U+208C", "SUBSCRIPT EQUALS SIGN" },
            { "₍", "U+208D", "SUBSCRIPT LEFT PARENTHESIS" },
            { "₎", "U+208E", "SUBSCRIPT RIGHT PARENTHESIS" },
            { "ₐ", "U+2090", "LATIN SUBSCRIPT SMALL LETTER A" },
            { "ₑ", "U+2091", "LATIN SUBSCRIPT SMALL LETTER E" },
            { "ₒ", "U+2092", "LATIN SUBSCRIPT SMALL LETTER O" },
            { "ₓ", "U+2093", "LATIN SUBSCRIPT SMALL LETTER X" },
            { "ₕ", "U+2095", "LATIN SUBSCRIPT SMALL LETTER H" },
            { "ₖ", "U+2096", "LATIN SUBSCRIPT SMALL LETTER K" },
            { "ₗ", "U+2097", "LATIN SUBSCRIPT SMALL LETTER L" },
            { "ₘ", "U+2098", "LATIN SUBSCRIPT SMALL LETTER M" },
            { "ₙ", "U+2099", "LATIN SUBSCRIPT SMALL LETTER N" },
            { "ₚ", "U+209A", "LATIN SUBSCRIPT SMALL LETTER P" },
            { "ₛ", "U+209B", "LATIN SUBSCRIPT SMALL LETTER S" },
            { "ₜ", "U+209C", "LATIN SUBSCRIPT SMALL LETTER T" },
        },
    },
    {
        title        = "Currency Symbols",
        unicodeRange = "U+20A0 - U+20CF",
        notes        = "International currency signs beyond ASCII dollar.",
        entries = {
            { "₠", "U+20A0", "EURO-CURRENCY SIGN" },
            { "₡", "U+20A1", "COLON SIGN" },
            { "₢", "U+20A2", "CRUZEIRO SIGN" },
            { "₣", "U+20A3", "FRENCH FRANC SIGN" },
            { "₤", "U+20A4", "LIRA SIGN" },
            { "₥", "U+20A5", "MILL SIGN" },
            { "₦", "U+20A6", "NAIRA SIGN" },
            { "₧", "U+20A7", "PESETA SIGN" },
            { "₨", "U+20A8", "RUPEE SIGN" },
            { "₩", "U+20A9", "WON SIGN" },
            { "₪", "U+20AA", "NEW SHEQEL SIGN" },
            { "₫", "U+20AB", "DONG SIGN" },
            { "€", "U+20AC", "EURO SIGN" },
            { "₭", "U+20AD", "KIP SIGN" },
            { "₮", "U+20AE", "TUGRIK SIGN" },
            { "₯", "U+20AF", "DRACHMA SIGN" },
            { "₰", "U+20B0", "GERMAN PENNY SIGN" },
            { "₱", "U+20B1", "PESO SIGN" },
            { "₲", "U+20B2", "GUARANI SIGN" },
            { "₳", "U+20B3", "AUSTRAL SIGN" },
            { "₴", "U+20B4", "HRYVNIA SIGN" },
            { "₵", "U+20B5", "CEDI SIGN" },
            { "₸", "U+20B8", "TENGE SIGN" },
            { "₹", "U+20B9", "INDIAN RUPEE SIGN" },
            { "₺", "U+20BA", "TURKISH LIRA SIGN" },
            { "₽", "U+20BD", "RUBLE SIGN" },
            { "₾", "U+20BE", "LARI SIGN" },
            { "₿", "U+20BF", "BITCOIN SIGN" },
        },
    },
    {
        title        = "Geometric Shapes Extended",
        unicodeRange = "U+1F780 - U+1F7FF",
        notes        = "Astral plane shapes (SMP). May render as tofu in fonts without SMP coverage.",
        entries = {
            { "🞀", "U+1F780", "BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE" },
            { "🞁", "U+1F781", "BLACK UP-POINTING ISOSCELES RIGHT TRIANGLE" },
            { "🞂", "U+1F782", "BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE" },
            { "🞃", "U+1F783", "BLACK DOWN-POINTING ISOSCELES RIGHT TRIANGLE" },
            { "🞄", "U+1F784", "BLACK SLIGHTLY SMALL CIRCLE" },
            { "🞅", "U+1F785", "MEDIUM BOLD WHITE CIRCLE" },
            { "🞆", "U+1F786", "BOLD WHITE CIRCLE" },
            { "🞇", "U+1F787", "HEAVY WHITE CIRCLE" },
            { "🞈", "U+1F788", "VERY HEAVY WHITE CIRCLE" },
            { "🞉", "U+1F789", "EXTREMELY HEAVY WHITE CIRCLE" },
            { "🞊", "U+1F78A", "WHITE CIRCLE CONTAINING BLACK SMALL CIRCLE" },
            { "🞍", "U+1F78D", "BLACK SLIGHTLY SMALL SQUARE" },
            { "🞎", "U+1F78E", "LIGHT WHITE SQUARE" },
            { "🞏", "U+1F78F", "MEDIUM WHITE SQUARE" },
            { "🞐", "U+1F790", "BOLD WHITE SQUARE" },
            { "🞑", "U+1F791", "HEAVY WHITE SQUARE" },
            { "🞒", "U+1F792", "VERY HEAVY WHITE SQUARE" },
            { "🞓", "U+1F793", "EXTREMELY HEAVY WHITE SQUARE" },
            { "🞔", "U+1F794", "WHITE SQUARE CONTAINING BLACK MEDIUM SQUARE" },
            { "🞕", "U+1F795", "WHITE SQUARE CONTAINING BLACK VERY SMALL SQUARE" },
            { "🞘", "U+1F798", "BLACK SLIGHTLY SMALL DIAMOND" },
            { "🞙", "U+1F799", "LIGHT WHITE DIAMOND" },
            { "🞚", "U+1F79A", "MEDIUM WHITE DIAMOND" },
            { "🞛", "U+1F79B", "BOLD WHITE DIAMOND" },
            { "🞜", "U+1F79C", "HEAVY WHITE DIAMOND" },
            { "🞝", "U+1F79D", "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND" },
            { "🞠", "U+1F7A0", "LIGHT FOUR POINTED BLACK CUSP" },
            { "🞡", "U+1F7A1", "MEDIUM FOUR POINTED BLACK CUSP" },
            { "🞢", "U+1F7A2", "BOLD FOUR POINTED BLACK CUSP" },
            { "🞣", "U+1F7A3", "HEAVY FOUR POINTED BLACK CUSP" },
            { "🟀", "U+1F7C0", "LIGHT FOUR POINTED BLACK STAR" },
            { "🟂", "U+1F7C2", "MEDIUM FOUR POINTED BLACK STAR" },
            { "🟃", "U+1F7C3", "MEDIUM FOUR POINTED PINWHEEL STAR" },
            { "🟄", "U+1F7C4", "REVERSE LIGHT FOUR POINTED PINWHEEL STAR" },
            { "🟅", "U+1F7C5", "LIGHT FIVE POINTED BLACK STAR" },
            { "🟆", "U+1F7C6", "HEAVY FIVE POINTED BLACK STAR" },
            { "🟇", "U+1F7C7", "MEDIUM SIX POINTED BLACK STAR" },
            { "🟉", "U+1F7C9", "MEDIUM EIGHT POINTED BLACK STAR" },
            { "🟊", "U+1F7CA", "HEAVY EIGHT POINTED BLACK STAR" },
            { "🟍", "U+1F7CD", "HEAVY TWELVE POINTED BLACK STAR" },
            { "🟐", "U+1F7D0", "CIRCLED EIGHT POINTED BLACK STAR" },
            { "🟕", "U+1F7D5", "HEAVY CIRCLED SALTIRE" },
        },
    },
    {
        title        = "Supplemental Arrows-A and -B (long arrows)",
        unicodeRange = "U+27F0 - U+297F",
        notes        = "Long arrows commonly used in technical/mathematical UI text.",
        entries = {
            { "⟰", "U+27F0", "UPWARDS QUADRUPLE ARROW" },
            { "⟱", "U+27F1", "DOWNWARDS QUADRUPLE ARROW" },
            { "⟲", "U+27F2", "ANTICLOCKWISE GAPPED CIRCLE ARROW" },
            { "⟳", "U+27F3", "CLOCKWISE GAPPED CIRCLE ARROW" },
            { "⟵", "U+27F5", "LONG LEFTWARDS ARROW" },
            { "⟶", "U+27F6", "LONG RIGHTWARDS ARROW" },
            { "⟷", "U+27F7", "LONG LEFT RIGHT ARROW" },
            { "⟸", "U+27F8", "LONG LEFTWARDS DOUBLE ARROW" },
            { "⟹", "U+27F9", "LONG RIGHTWARDS DOUBLE ARROW" },
            { "⟺", "U+27FA", "LONG LEFT RIGHT DOUBLE ARROW" },
            { "⟻", "U+27FB", "LONG LEFTWARDS ARROW FROM BAR" },
            { "⟼", "U+27FC", "LONG RIGHTWARDS ARROW FROM BAR" },
            { "⟽", "U+27FD", "LONG LEFTWARDS DOUBLE ARROW FROM BAR" },
            { "⟾", "U+27FE", "LONG RIGHTWARDS DOUBLE ARROW FROM BAR" },
            { "⟿", "U+27FF", "LONG RIGHTWARDS SQUIGGLE ARROW" },
            { "⤴", "U+2934", "ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS" },
            { "⤵", "U+2935", "ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS" },
            { "⤶", "U+2936", "ARROW POINTING DOWNWARDS THEN CURVING LEFTWARDS" },
            { "⤷", "U+2937", "ARROW POINTING DOWNWARDS THEN CURVING RIGHTWARDS" },
            { "⤸", "U+2938", "RIGHT-SIDE ARC CLOCKWISE ARROW" },
            { "⤹", "U+2939", "LEFT-SIDE ARC ANTICLOCKWISE ARROW" },
            { "⤺", "U+293A", "TOP ARC ANTICLOCKWISE ARROW" },
            { "⤻", "U+293B", "BOTTOM ARC ANTICLOCKWISE ARROW" },
            { "⥀", "U+2940", "ANTICLOCKWISE CLOSED CIRCLE ARROW" },
            { "⥁", "U+2941", "CLOCKWISE CLOSED CIRCLE ARROW" },
            { "⥂", "U+2942", "RIGHTWARDS ARROW ABOVE SHORT LEFTWARDS ARROW" },
            { "⥃", "U+2943", "LEFTWARDS ARROW ABOVE SHORT RIGHTWARDS ARROW" },
            { "⥄", "U+2944", "SHORT RIGHTWARDS ARROW ABOVE LEFTWARDS ARROW" },
            { "⥆", "U+2946", "LEFTWARDS ARROW WITH PLUS BELOW" },
            { "⥇", "U+2947", "RIGHTWARDS ARROW WITH PLUS BELOW" },
            { "⥈", "U+2948", "LEFT RIGHT ARROW THROUGH SMALL CIRCLE" },
            { "⥉", "U+2949", "UPWARDS TWO-HEADED ARROW FROM SMALL CIRCLE" },
            { "⥊", "U+294A", "LEFT BARB UP RIGHT BARB DOWN HARPOON" },
            { "⥋", "U+294B", "LEFT BARB DOWN RIGHT BARB UP HARPOON" },
        },
    },
}
