--[[
    GeRODPS_Tools / SpellOverrideListView.lua

    "Spell Override Cache" tool — view + export learned override pairs.

    Two data sources (queried via GeRODPS.GetAllOverridePairs):
      • manual: GeRODPS.SpellOverrideList (hard-coded by dev)
      • auto:   GeRODPS.dbGlobal.spellOverrideMap (runtime auto-learned)

    Display: sortable read-only table (class → spec → override).

    Export: opens a popup with a MultiLineEditBox containing the merged
    entries formatted as Lua source — sorted by class (WoW CLASS_SORT_ORDER),
    then by spec, then by overrideID. Dev copies the block into
    SpellOverrideList.lua to promote auto entries to hard-coded.

    Public:
        GeRODPS_Tools.ShowSpellOverrideListView()
        GeRODPS_Tools.HideSpellOverrideListView()
        GeRODPS_Tools.ToggleSpellOverrideListView()
]]

GeRODPS_Tools = GeRODPS_Tools or {}
local TOOL = GeRODPS_Tools

local FRAME_NAME    = "GeRODPS_ToolsSpellOverrideListViewFrame"
local SCREEN_MARGIN = 50
local ROW_H         = 18

local DEFAULT_W, DEFAULT_H = 880, 540
local MIN_W,     MIN_H     = 640, 360
local MAX_W,     MAX_H     = 1400, 900

-- Column widths sum to 800 (frame content area = 880 - 40 margins ≈ 840).
local COL = {
    { key="class",        title="Class",            w=110 },
    { key="spec",         title="Spec",             w=110 },
    { key="overrideName", title="Override Spell",   w=180 },
    { key="overrideID",   title="ID",               w=70  },
    { key="baseName",     title="Base Spell",       w=180 },
    { key="baseID",       title="ID",               w=70  },
    { key="source",       title="Source",           w=70  },
}
local CONTENT_W = 0
for _, c in ipairs(COL) do CONTENT_W = CONTENT_W + c.w end

-- WoW class sort order — fall back to alpha if global missing.
local CLASS_SORT_ORDER = CLASS_SORT_ORDER or {
    "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "EVOKER", "HUNTER", "MAGE",
    "MONK", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR",
}
local _classRank = {}
for i, c in ipairs(CLASS_SORT_ORDER) do _classRank[c] = i end
local function ClassRank(c) return _classRank[c] or 99 end

-- ============================================================
-- DB (geometry only)
-- ============================================================

local function GetDB()
    GeRODPS_ToolsDB = GeRODPS_ToolsDB or {}
    GeRODPS_ToolsDB.spellOverrideView = GeRODPS_ToolsDB.spellOverrideView or {}
    return GeRODPS_ToolsDB.spellOverrideView
end

-- ============================================================
-- Sorted snapshot from GeRODPS.GetAllOverridePairs
-- Returns an array of entries: { overrideID, base, class, spec,
--                                overrideName, baseName, source }
-- Sorted by class rank → spec → overrideID.
-- ============================================================

local function GetSortedSnapshot()
    local entries = {}
    if not (GeRODPS and GeRODPS.GetAllOverridePairs) then return entries end
    local pairs_ = GeRODPS.GetAllOverridePairs()
    for ovID, e in pairs(pairs_) do
        entries[#entries + 1] = {
            overrideID   = ovID,
            base         = e.base,
            class        = e.class or "UNKNOWN",
            spec         = e.spec  or "Unknown",
            overrideName = e.overrideName or tostring(ovID),
            baseName     = e.baseName     or tostring(e.base),
            source       = e.source or "auto",
        }
    end
    table.sort(entries, function(a, b)
        local ra, rb = ClassRank(a.class), ClassRank(b.class)
        if ra ~= rb then return ra < rb end
        if a.spec ~= b.spec then return a.spec < b.spec end
        return a.overrideID < b.overrideID
    end)
    return entries
end

-- ============================================================
-- Export string builder
-- Produces a Lua source block — drop-in pasteable into
-- SpellOverrideList.lua. Format mirrors the existing entries
-- (class header comment, then aligned KV entries).
-- ============================================================

local function BuildExportText(entries)
    local lines = {}
    local function push(s) lines[#lines + 1] = s end

    push("    -- Generated by GeRODPS_Tools → Spell Override Cache → Export")
    push("    -- " .. date("%Y-%m-%d %H:%M:%S") .. "  |  total: " .. #entries)
    push("")

    local lastClass = nil
    for _, e in ipairs(entries) do
        if e.class ~= lastClass then
            if lastClass then push("") end
            push("    -- ============================================================")
            push("    -- " .. e.class)
            push("    -- ============================================================")
            push("")
            lastClass = e.class
        end
        -- Inline header comment for the pair
        push(string.format(
            "    -- %s | %s → %s",
            e.spec, e.overrideName, e.baseName))
        push(string.format(
            "    [%d] = { base = %d, class = %q, spec = %q,\n             overrideName = %q, baseName = %q },",
            e.overrideID, e.base, e.class, e.spec, e.overrideName, e.baseName))
    end

    return table.concat(lines, "\n")
end

-- ============================================================
-- State
-- ============================================================

local frame
local scroll
local content
local rows = {}        -- pre-created Frames, reused across renders
local statusFS
local _exportPopup

-- ============================================================
-- Geometry persistence
-- ============================================================

local function SavePosition(self)
    local db = GetDB()
    local point, _, relPoint, x, y = self:GetPoint(1)
    db.point, db.relPoint, db.x, db.y = point, relPoint, x, y
end

local function SaveSize(self)
    local db = GetDB()
    db.w, db.h = self:GetWidth(), self:GetHeight()
end

local function ApplySavedGeometry(self)
    local db = GetDB()
    local screenW = UIParent:GetWidth()
    local screenH = UIParent:GetHeight()

    local w = db.w or DEFAULT_W
    local h = db.h or DEFAULT_H
    if w > screenW - 2 * SCREEN_MARGIN then w = screenW - 2 * SCREEN_MARGIN end
    if h > screenH - 2 * SCREEN_MARGIN then h = screenH - 2 * SCREEN_MARGIN end
    if w < MIN_W then w = MIN_W end
    if h < MIN_H then h = MIN_H end

    self:ClearAllPoints()
    if db.point and db.relPoint and db.x and db.y then
        self:SetPoint(db.point, UIParent, db.relPoint, db.x, db.y)
    else
        self:SetPoint("CENTER")
    end
    self:SetSize(w, h)
end

-- ============================================================
-- Row pool — build once, reuse via SetText
-- ============================================================

local function BuildRowPool(parent, totalRows)
    for r = 1, totalRows do
        local row = CreateFrame("Frame", nil, parent)
        row:SetSize(CONTENT_W, ROW_H)
        row:SetPoint("TOPLEFT", parent, "TOPLEFT", 0, -(r - 1) * ROW_H)
        if r % 2 == 0 then
            local bg = row:CreateTexture(nil, "BACKGROUND")
            bg:SetAllPoints()
            bg:SetColorTexture(0.08, 0.08, 0.08, 0.5)
        end
        row.fs = {}
        local x = 0
        for c, def in ipairs(COL) do
            local fs = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
            fs:SetPoint("LEFT", row, "LEFT", x + 4, 0)
            fs:SetWidth(def.w - 8)
            fs:SetHeight(ROW_H)
            fs:SetJustifyH("LEFT")
            fs:SetJustifyV("MIDDLE")
            fs:SetText("")
            row.fs[c] = fs
            x = x + def.w
        end
        rows[r] = row
    end
end

-- ============================================================
-- Render — sync rows to current snapshot
-- ============================================================

local function Render()
    local entries = GetSortedSnapshot()
    -- Grow pool if needed
    if #entries > #rows and content then
        BuildRowPool(content, #entries)
    end
    -- Update visible content height so the scrollbar maxes correctly
    if content then
        content:SetHeight(math.max(1, #rows * ROW_H))
    end

    for r = 1, #rows do
        local row = rows[r]
        local e = entries[r]
        if e then
            row.fs[1]:SetText(e.class)
            row.fs[2]:SetText(e.spec)
            row.fs[3]:SetText(e.overrideName)
            row.fs[4]:SetText(tostring(e.overrideID))
            row.fs[5]:SetText(e.baseName)
            row.fs[6]:SetText(tostring(e.base))
            -- Color-code source: manual = yellow, auto = grey
            if e.source == "manual" then
                row.fs[7]:SetText("|cFFFFD200manual|r")
            else
                row.fs[7]:SetText("|cFF888888auto|r")
            end
            row:Show()
        else
            for c = 1, #COL do row.fs[c]:SetText("") end
        end
    end

    if statusFS then
        local autoCount, manualCount = 0, 0
        for _, e in ipairs(entries) do
            if e.source == "manual" then manualCount = manualCount + 1
            else autoCount = autoCount + 1 end
        end
        statusFS:SetText(string.format(
            "Total: %d  (manual: %d, auto: %d)",
            #entries, manualCount, autoCount))
    end
end

-- ============================================================
-- Export popup
-- ============================================================

local function ShowExportPopup()
    if _exportPopup and _exportPopup:IsShown() then
        _exportPopup:Raise()
        return
    end

    local entries = GetSortedSnapshot()
    local text = BuildExportText(entries)

    if not _exportPopup then
        local f = CreateFrame("Frame", "GeRODPS_ToolsSpellOverrideExportFrame",
            UIParent, "BasicFrameTemplateWithInset")
        _exportPopup = f
        f:SetSize(720, 520)
        f:SetPoint("CENTER")
        f:SetFrameStrata("FULLSCREEN_DIALOG")
        f:SetToplevel(true)
        f:SetMovable(true)
        f:EnableMouse(true)
        f:SetClampedToScreen(true)
        f:RegisterForDrag("LeftButton")
        f:SetScript("OnDragStart", f.StartMoving)
        f:SetScript("OnDragStop",  f.StopMovingOrSizing)
        if f.TitleText then
            f.TitleText:SetText("Spell Override Cache — Export")
        end
        tinsert(UISpecialFrames, "GeRODPS_ToolsSpellOverrideExportFrame")

        local hint = f:CreateFontString(nil, "OVERLAY", "GameFontDisableSmall")
        hint:SetPoint("TOPLEFT", f, "TOPLEFT", 12, -30)
        hint:SetText("Ctrl+A then Ctrl+C to copy.  Paste into SpellOverrideList.lua.")

        local sf = CreateFrame("ScrollFrame", "$parentScroll",
            f, "UIPanelScrollFrameTemplate")
        sf:SetPoint("TOPLEFT",     f, "TOPLEFT",     12, -50)
        sf:SetPoint("BOTTOMRIGHT", f, "BOTTOMRIGHT", -32, 12)

        local eb = CreateFrame("EditBox", nil, sf)
        eb:SetMultiLine(true)
        eb:SetAutoFocus(false)
        eb:SetFontObject(ChatFontNormal)
        eb:SetWidth(sf:GetWidth())
        eb:SetMaxLetters(0)
        eb:SetCountInvisibleLetters(false)
        eb:EnableMouse(true)
        eb:SetScript("OnEscapePressed", function(self) self:ClearFocus() end)
        eb:SetScript("OnCursorChanged", function(self, _, y, _, ch)
            ScrollingEdit_OnCursorChanged(self, 0, y, 0, ch)
        end)
        sf:SetScrollChild(eb)
        f.editBox = eb
    end

    _exportPopup.editBox:SetText(text)
    _exportPopup:Show()
    _exportPopup:Raise()
end

-- ============================================================
-- Frame builder
-- ============================================================

local function CreateFrameOnce()
    if frame then return frame end

    frame = CreateFrame("Frame", FRAME_NAME, UIParent, "BasicFrameTemplateWithInset")
    frame:SetFrameStrata("HIGH")
    frame:SetToplevel(true)
    frame:SetClampedToScreen(true)
    frame:SetMovable(true)
    frame:EnableMouse(true)
    frame:SetUserPlaced(true)
    frame:RegisterForDrag("LeftButton")
    frame:SetScript("OnDragStart", frame.StartMoving)
    frame:SetScript("OnDragStop", function(self)
        self:StopMovingOrSizing()
        SavePosition(self)
    end)
    frame:SetResizable(true)
    if frame.SetResizeBounds then
        frame:SetResizeBounds(MIN_W, MIN_H, MAX_W, MAX_H)
    elseif frame.SetMinResize then
        frame:SetMinResize(MIN_W, MIN_H)
        frame:SetMaxResize(MAX_W, MAX_H)
    end

    if frame.TitleText then
        frame.TitleText:SetText("GeRODPS Tools — Spell Override Cache")
    end

    local inset = frame.Inset or frame

    -- ── Toolbar ──────────────────────────────────────────
    local toolbar = CreateFrame("Frame", nil, inset)
    toolbar:SetHeight(28)
    toolbar:SetPoint("TOPLEFT", inset, "TOPLEFT", 8, -4)
    toolbar:SetPoint("TOPRIGHT", inset, "TOPRIGHT", -8, -4)

    local refreshBtn = CreateFrame("Button", nil, toolbar, "UIPanelButtonTemplate")
    refreshBtn:SetSize(90, 22)
    refreshBtn:SetPoint("LEFT", toolbar, "LEFT", 0, 0)
    refreshBtn:SetText("Refresh")
    refreshBtn:SetScript("OnClick", Render)

    local exportBtn = CreateFrame("Button", nil, toolbar, "UIPanelButtonTemplate")
    exportBtn:SetSize(90, 22)
    exportBtn:SetPoint("LEFT", refreshBtn, "RIGHT", 8, 0)
    exportBtn:SetText("Export")
    exportBtn:SetScript("OnClick", ShowExportPopup)

    local clearBtn = CreateFrame("Button", nil, toolbar, "UIPanelButtonTemplate")
    clearBtn:SetSize(120, 22)
    clearBtn:SetPoint("LEFT", exportBtn, "RIGHT", 8, 0)
    clearBtn:SetText("Clear Auto Cache")
    clearBtn:SetScript("OnClick", function()
        if GeRODPS and GeRODPS.ClearAutoOverrideCache then
            GeRODPS.ClearAutoOverrideCache()
            Render()
        end
    end)

    statusFS = toolbar:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    statusFS:SetPoint("LEFT", clearBtn, "RIGHT", 16, 0)
    statusFS:SetText("")

    -- ── Header row ────────────────────────────────────────
    local header = CreateFrame("Frame", nil, inset)
    header:SetHeight(ROW_H)
    header:SetPoint("TOPLEFT", toolbar, "BOTTOMLEFT", 0, -4)
    header:SetPoint("TOPRIGHT", toolbar, "BOTTOMRIGHT", 0, -4)
    local hbg = header:CreateTexture(nil, "ARTWORK")
    hbg:SetAllPoints()
    hbg:SetColorTexture(0.15, 0.10, 0.05, 0.9)
    local hx = 0
    for c, def in ipairs(COL) do
        local fs = header:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        fs:SetPoint("LEFT", header, "LEFT", hx + 4, 0)
        fs:SetWidth(def.w - 8)
        fs:SetHeight(ROW_H)
        fs:SetJustifyH("LEFT")
        fs:SetJustifyV("MIDDLE")
        fs:SetText("|cFFFFD200" .. def.title .. "|r")
        hx = hx + def.w
    end

    -- ── ScrollFrame for the row list ──────────────────────
    scroll = CreateFrame("ScrollFrame", nil, inset, "UIPanelScrollFrameTemplate")
    scroll:SetPoint("TOPLEFT", header, "BOTTOMLEFT", 0, -4)
    scroll:SetPoint("BOTTOMRIGHT", inset, "BOTTOMRIGHT", -28, 8)

    content = CreateFrame("Frame", nil, scroll)
    content:SetSize(CONTENT_W, ROW_H)   -- height grows in Render
    scroll:SetScrollChild(content)

    -- Pre-create 64 rows (auto-grows in Render if more entries arrive)
    BuildRowPool(content, 64)

    -- Resize handle (bottom-right corner)
    local resize = CreateFrame("Button", nil, frame)
    resize:SetSize(16, 16)
    resize:SetPoint("BOTTOMRIGHT", -4, 4)
    resize:EnableMouse(true)
    resize:SetNormalTexture("Interface/ChatFrame/UI-ChatIM-SizeGrabber-Up")
    resize:SetHighlightTexture("Interface/ChatFrame/UI-ChatIM-SizeGrabber-Highlight")
    resize:SetPushedTexture("Interface/ChatFrame/UI-ChatIM-SizeGrabber-Down")
    resize:SetScript("OnMouseDown", function(_, button)
        if button == "LeftButton" then
            frame:StopMovingOrSizing()
            frame:StartSizing("BOTTOMRIGHT")
        end
    end)
    resize:SetScript("OnMouseUp", function(_, button)
        if button == "LeftButton" then
            frame:StopMovingOrSizing()
            SaveSize(frame)
        end
    end)

    table.insert(UISpecialFrames, FRAME_NAME)
    ApplySavedGeometry(frame)
    frame:Hide()
    return frame
end

-- ============================================================
-- Public API
-- ============================================================

function TOOL.ShowSpellOverrideListView()
    local f = CreateFrameOnce()
    if not f:IsShown() then
        ApplySavedGeometry(f)
        f:Show()
        Render()
    end
end

function TOOL.HideSpellOverrideListView()
    if frame and frame:IsShown() then frame:Hide() end
end

function TOOL.ToggleSpellOverrideListView()
    local f = CreateFrameOnce()
    if f:IsShown() then
        f:Hide()
    else
        ApplySavedGeometry(f)
        f:Show()
        Render()
    end
end

-- Register into the minimap menu (Core.lua provides RegisterTool)
if TOOL.RegisterTool then
    TOOL.RegisterTool("Spell Override Cache", TOOL.ToggleSpellOverrideListView)
end
